import { House } from '../models/house';

export const HOUSELIST: Array<House> = [
  {
    id: 1,
    name: 'Maison mémoire du temps',
    price: 100,
    place: 'Cannes',
    picture: 'assets/b.png',
    disponible: true,
  },
  {
    id: 2,
    name: 'Maison papillon en fleurs',
    price: 250,
    place: 'Marseille',
    picture: 'assets/c.png',
    disponible: true,
  },
  {
    id: 3,
    name: 'Maison secret du jardin',
    price: 720,
    place: 'Monaco',
    picture: 'assets/m.png',
    disponible: true,
  },
  {
    id: 4,
    name: 'Maison dautrefois',
    price: 180,
    place: 'Nice',
    picture: 'assets/n.png',
    disponible: true,
  },
  {
    id: 5,
    name: 'La maison champêtre',
    price: 120,
    place: 'Marseille',
    picture: 'assets/f.png',
    disponible: true,
  },
  {
    id: 6,
    name: 'Coin de passé raffiné',
    price: 5100,
    place: 'Monaco',
    picture: 'assets/g.png',
    disponible: true,
  },
  {
    id: 7,
    name: 'Coin de paradis',
    price: 330,
    place: 'Marseille',
    picture: 'assets/h.png',
    disponible: true,
  },
  {
    id: 8,
    name: 'Maison des souvenirs',
    price: 60,
    place: 'Nice',
    picture: 'assets/i.png',
    disponible: true,
  },
  {
    id: 9,
    name: 'Maison sable',
    price: 80,
    place: 'Marseille',
    picture: 'assets/j.png',
    disponible: true,
  },
  {
    id: 10,
    name: 'Escale bleue azur',
    price: 220,
    place: 'Cannes',
    picture: 'assets/l.png',
    disponible: true,
  },
  {
    id: 11,
    name: 'Villa sérénité',
    price: 90,
    place: 'Nice',
    picture: 'assets/p.png',
    disponible: true,
  },
  {
    id: 12,
    name: 'Douce brise de la mer',
    price: 150,
    place: 'Monaco',
    picture: 'assets/o.png',
    disponible: true,
  },
];
